# Generated by Django 4.0.5 on 2022-06-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_rename_pet_adocao_pet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adocao',
            old_name='pet_id',
            new_name='pet',
        ),
    ]
